import React from 'react'
import Head from 'next/head'
import Navbar from '../Navbar/Navbar'
import SideBarLeft from '../SideBarLeft/SideBarLeft'
import SideBarRight from '../SideRight/SideBarRight'
import styles from './Layout.module.css'

const user = {
  name: 'Kevin Stardust',
  position: 'Cosmic Explorer at Celestial Voyagers Incorporated'
}

function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>GreenMap Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className={styles.mainContainer}>
          <SideBarLeft
            userName={user.name}
            position={user.position}
          />
          <div>
            {children}
          </div>
          <SideBarRight />
        </div>
      </main>
    </div>
  )
}

export default Layout