import React from 'react'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import SideBarLeft from '../components/SideBarLeft'
import SideBarRight from '../components/SideBarRight'
import styles from './Layout.module.css'

function Layout({ children }) {
  const user = {
    name: 'Kevin Stardust',
    position: 'Cosmic Explorer at Celestial Voyagers Incorporated'
  }
  return (
    <div>
      <Head>
        <title>Relp Test App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className={styles.mainContainer}>
          <SideBarLeft userName={user.name} position={user.position}/>
          <div className={styles.childrenContainer}>
            {children}
          </div>
          <SideBarRight />
        </div>
      </main>
    </div>
  )
}

export default Layout